name: UniCM-env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.5=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.10.0.4=0
  - libcurand=10.3.6.39=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py311h06a4308_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.14=h5eee18b_0
  - pillow=10.3.0=py311h5eee18b_0
  - pip=24.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - pytorch=2.0.1=py3.11_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.0.2=py311_cu117
  - torchtriton=2.0.0=py311
  - torchvision=0.15.2=py311_cu117
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.33.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - anyio==4.7.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - cartopy==0.24.1
      - cdsapi==0.7.5
      - certifi==2024.12.14
      - cf-xarray==0.10.0
      - cffi==1.17.1
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.0
      - climpred==2.5.0
      - cloudpickle==3.1.0
      - comm==0.2.2
      - cssselect2==0.8.0
      - dask==2024.12.1
      - datapi==0.4.0
      - debugpy==1.8.11
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.30.2
      - docopt==0.6.2
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - executing==2.1.0
      - fastdtw==0.3.4
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - gputil==1.4.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.12.3
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - llvmlite==0.43.0
      - locket==1.0.0
      - lxml==6.0.2
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - multidict==6.0.5
      - multiurl==0.3.5
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netcdf4==1.7.2
      - notebook==7.3.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - openpyxl==3.1.5
      - overrides==7.7.0
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - patsy==0.5.6
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - properscoring==0.1
      - protobuf==4.23.4
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pymetis==2023.1.1
      - pynvml==11.5.0
      - pyshp==2.3.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.0
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.7.24
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - scikit-learn==1.5.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - setuptools==75.6.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - svgutils==0.3.4
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - toolz==1.0.0
      - torch-geometric==2.5.3
      - tornado==6.4.2
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - xarray==2024.11.0
      - xhistogram==0.3.2
      - xskillscore==0.0.26
      - yarg==0.1.9
      - yarl==1.9.4