name: UniCM-env
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.*
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pip
  - pip:
      - torch-geometric==2.5.3
      - timm
      - xarray
      - netcdf4
      - scikit-learn
      - numba
      - pynvml
